### ISSUE TITLE
Cargo clippy crashes in a subdirectory

### ISSUE THREAD

**Issue by vorner** [rust-lang-nursery/rust-clippy#1515]
While the usual cargo commands (build, test, …) work fine when run from a subdirectory, cargo clippy crashes. It works OK in the project top-level directory. I believe the following shell log contains everything important:

```
  101 vorner@ruth ~/prog/tokio-jsonrpc/src (master) 71%
$ RUST_BACKTRACE=1 cargo clippy
thread 'main' panicked at 'could not find matching package', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/option.rs:715
stack backtrace:
   1:     0x7fe4a567146c - std::sys::imp::backtrace::tracing::imp::write::hf7294f5e24536b4a
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x7fe4a567f91e - std::panicking::default_hook::{{closure}}::h9a07d0b00c43fbee
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x7fe4a567f524 - std::panicking::default_hook::hf25feff2d08bf39b
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:367
   4:     0x7fe4a567fdbb - std::panicking::rust_panic_with_hook::h4cb8c6fbb8386ccf
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:555
   5:     0x7fe4a567fc54 - std::panicking::begin_panic::heb3517ba798e470b
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:517
   6:     0x7fe4a567fb79 - std::panicking::begin_panic_fmt::h7bf5635a07d66272
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:501
   7:     0x7fe4a567fb07 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:477
   8:     0x7fe4a56bcf8d - core::panicking::panic_fmt::hd806cbc840443dbf
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:69
   9:     0x7fe4a56bd01d - core::option::expect_failed::h1976fc4942dde223
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/option.rs:715
  10:     0x56250018d04d - cargo_clippy::main::h755a1b9836dba10c
  11:     0x7fe4a5688bfa - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  12:     0x7fe4a5680a16 - std::rt::lang_start::h0637c2e100ff36fc
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:436
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:361
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/rt.rs:57
  13:     0x7fe4a4b4b67f - __libc_start_main
  14:     0x562500181098 - _start
  15:                0x0 - <unknown>
  101 vorner@ruth ~/prog/tokio-jsonrpc/src (master) 71%
$ clipp^C
  130 vorner@ruth ~/prog/tokio-jsonrpc/src (master) 71%
$ cargo clippy --version
0.0.113
10:13 vorner@ruth ~/prog/tokio-jsonrpc/src (master) 71%
$ cargo clippy --version --verbose
0.0.113
10:13 vorner@ruth ~/prog/tokio-jsonrpc/src (master) 71%
$ rustc --version --verbose
rustc 1.17.0-nightly (ea7a6486a 2017-02-04)
binary: rustc
commit-hash: ea7a6486a26af085862cd7a5596bb69e83d85e12
commit-date: 2017-02-04
host: x86_64-unknown-linux-gnu
release: 1.17.0-nightly
LLVM version: 3.9
10:13 vorner@ruth ~/prog/tokio-jsonrpc/src (master) 71%
$ cd ..
10:13 vorner@ruth ~/prog/tokio-jsonrpc (master) 71%
$ cargo clippy
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
   Compiling tokio-jsonrpc v0.1.0 (file:///home/vorner/prog/tokio-jsonrpc)
    Finished dev [unoptimized + debuginfo] target(s) in 0.32 secs
   Compiling tokio-jsonrpc v0.1.0 (file:///home/vorner/prog/tokio-jsonrpc)
    Finished dev [unoptimized + debuginfo] target(s) in 0.74 secs
10:13 vorner@ruth ~/prog/tokio-jsonrpc (master) 71%
```

It would be nice if it could find the top-level directory like all the other commands do.

**Comment by SirDoctors** [comment]
So this is interesting, I'm having the exact apposite problem, where I can't use clippy on the whole workspace at once, but I can use it in individual projects.
```cargo
╭─   17:45:31   …/git/alchemist     dede3c7  github_checks                                                                                                                     ✓  2262  97%     -50 
╰─ RUST_BACKTRACE=1 cargo clippy
thread 'main' panicked at 'could not find matching package', /checkout/src/libcore/option.rs:785
stack backtrace:
   1:     0x7fc710cc9009 - std::sys::imp::backtrace::tracing::imp::write::hbb14611794d3841b
                        at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x7fc710cd769e - std::panicking::default_hook::{{closure}}::h6ed906c7818ac88c
                        at /checkout/src/libstd/panicking.rs:351
   3:     0x7fc710cd72a4 - std::panicking::default_hook::h23eeafbf7c1c05c3
                        at /checkout/src/libstd/panicking.rs:367
   4:     0x7fc710cd7afb - std::panicking::rust_panic_with_hook::hd0067971b6d1240e
                        at /checkout/src/libstd/panicking.rs:545
   5:     0x7fc710cd7984 - std::panicking::begin_panic::h1fd1f10a3de8f902
                        at /checkout/src/libstd/panicking.rs:507
   6:     0x7fc710cd78f9 - std::panicking::begin_panic_fmt::haa043917b5d6f21b
                        at /checkout/src/libstd/panicking.rs:491
   7:     0x7fc710cd7887 - rust_begin_unwind
                        at /checkout/src/libstd/panicking.rs:467
   8:     0x7fc710d13fad - core::panicking::panic_fmt::he9c7f335d160b59d
                        at /checkout/src/libcore/panicking.rs:69
   9:     0x7fc710d1403d - core::option::expect_failed::h4aee2e09812a5db0
                        at /checkout/src/libcore/option.rs:785
  10:     0x555788354bdd - cargo_clippy::main::hb798bd359356fbfc
  11:     0x7fc710ce09aa - __rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:98
  12:     0x7fc710cd8796 - std::rt::lang_start::hb7fc7ec87b663023
                        at /checkout/src/libstd/panicking.rs:429
                        at /checkout/src/libstd/panic.rs:361
                        at /checkout/src/libstd/rt.rs:57
  13:     0x7fc7101884e0 - __libc_start_main
  14:     0x555788348d49 - _start
  15:                0x0 - <unknown>
╭─   17:45:36   …/git/alchemist     dede3c7  github_checks                                                                                                                 101 ↵  2263  97%     -50 
╰─ cd alchemist 
╭─   17:46:27   …/alchemist/alchemist     dede3c7  github_checks                                                                                                               ✓  2264  96%     -47 
╰─ RUST_BACKTRACE=1 cargo clippy
   Compiling unicode-segmentation v1.1.0
   Compiling winapi-build v0.1.1
   Compiling libsqlite3-sys v0.4.0
   Compiling kernel32-sys v0.2.2
   Compiling vec_map v0.6.0
   Compiling strsim v0.6.0
   Compiling quote v0.3.13
   Compiling winapi v0.2.8
   Compiling syn v0.10.8
   Compiling alchemist v0.4.0 (file:///home/benjamin/git/alchemist/alchemist)
error: expected one of `.`, `;`, `?`, or an operator, found `if`
  --> build.rs:16:5
   |
16 |     if ( diesel === 127) {
   |     ^^

error: Could not compile `alchemist`.
Build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by vorner** [comment]
I don't think it is opposite. I don't have a workspace with subprojects, I have a single cargo project. I tried to run it inside the `src` directory.

It seems clippy needs to be run where the relevant `Cargo.toml` is located for the code to be checked.

**Comment by SirDoctors** [comment]
ahh so the issue lies with clippy crashing when ``Cargo.toml`` isn't present in the main path.

**Comment by vorner** [comment]
Maybe. I haven't looked into it to see what exactly is causing it, but it could certainly explain the error message and the crash.

**Comment by clarcharr** [comment]
This is still happening in the latest version; it doesn't crash as awfully though.

**Comment by phansch** [comment]
Looks like both of these issues are fixed in the latest release. I was able to run clippy in a subdirectory of `tokio-jsonrpc` and also in the root directory of `alchemist`.

I'm going ahead and close the issue, but feel free to re-open if it still happens in other places.
