### ISSUE TITLE
rustc panic on build

### ISSUE THREAD

**Issue by camsteffen** [rust-lang-nursery/rust-clippy#1756]
When I run `cargo clippy` on `https://github.com/PistonDevelopers/image.git` the build fails with the following output. It builds fine with `cargo build`. What's the problem?

```
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: DistinctSources(DistinctSources { begin: ("src/gif.rs", BytePos(182247)), end: ("<try macros>", BytePos(4594539)) })', src/libcore/result.rs:859
stack backtrace:
   0:        0x1140a10d3 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h34a7b169ac42b490
   1:        0x1140ae134 - std::panicking::default_hook::{{closure}}::hcc7f46907143dca1
   2:        0x1140add4c - std::panicking::default_hook::h9cd165f254d86e53
   3:        0x1140b0817 - std::panicking::rust_panic_with_hook::h2bd2f0b446f0face
   4:        0x1140b06b4 - std::panicking::begin_panic::h1732f61ecaaa434e
   5:        0x1140b0622 - std::panicking::begin_panic_fmt::h2948dd4668f99175
   6:        0x1140b0587 - rust_begin_unwind
   7:        0x1140ed750 - core::panicking::panic_fmt::hb2e726f3b579b19d
   8:        0x1135fc046 - core::result::unwrap_failed::h7e43a91a65eae380
   9:        0x11360349d - <rustc_errors::emitter::EmitterWriter as rustc_errors::emitter::Emitter>::emit::h857d30d5f2c34c0a
  10:        0x1136010bd - rustc_errors::diagnostic_builder::DiagnosticBuilder::emit::hbad34e68358ad9cb
  11:        0x10e54a0ef - <clippy_lints::if_let_redundant_pattern_matching::Pass as rustc::lint::LateLintPass<'a, 'tcx>>::check_expr::h4822762fcbd44123
  12:        0x10fb8558d - rustc::lint::context::LintContext::with_lint_attrs::h95b7a4c6241bbf22
  13:        0x10fb8e828 - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_block::h88f0441b0734d50f
  14:        0x10fb85756 - rustc::lint::context::LintContext::with_lint_attrs::h95b7a4c6241bbf22
  15:        0x10fb8cb1e - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_body::h165852f07b8224dd
  16:        0x10fb8c9ed - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_nested_body::hdc2e3165f4a6eb0b
  17:        0x10fb8d7f0 - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_fn::hc91092b80e68da46
  18:        0x10fac7421 - rustc::hir::intravisit::walk_impl_item::h56a173e37f498d85
  19:        0x10fb82785 - rustc::lint::context::LintContext::with_lint_attrs::h7d3ebd8611211f87
  20:        0x10fab6ef2 - rustc::hir::intravisit::Visitor::visit_nested_impl_item::h08e1f5957ba11f2b
  21:        0x10fab986b - rustc::hir::intravisit::walk_item::h8dd6e6acb4e483a9
  22:        0x10fb874c2 - rustc::lint::context::LintContext::with_lint_attrs::hcb126365ed39a359
  23:        0x10fb8e516 - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_mod::hf381177eaed72ca6
  24:        0x10fab98df - rustc::hir::intravisit::walk_item::h8dd6e6acb4e483a9
  25:        0x10fb874c2 - rustc::lint::context::LintContext::with_lint_attrs::hcb126365ed39a359
  26:        0x10fb8e516 - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_mod::hf381177eaed72ca6
  27:        0x10fb9359a - rustc::lint::context::check_crate::hf939b94bd95a14b3
  28:        0x10e8640da - rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}::h4d214f00df4ddfbc
  29:        0x10e84e27b - rustc_driver::driver::phase_3_run_analysis_passes::h9ba279e7e8dbf3ef
  30:        0x10e835eed - rustc_driver::driver::compile_input::hdef5f220808181b7
  31:        0x10e881da0 - rustc_driver::run_compiler::h20e73f67d559ff12
  32:        0x10e440b29 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha252787f33869b0a
  33:        0x10e4421b7 - std::panicking::try::do_call::h198ccde26b4092f9
  34:        0x1140b380a - __rust_maybe_catch_panic
  35:        0x10e44956c - <F as alloc::boxed::FnBox<A>>::call_box::hd564c19b31f9ab11
  36:        0x1140ad175 - std::sys::imp::thread::Thread::new::thread_start::h5852519f9f48a1f2
  37:     0x7fffb53359ae - _pthread_body
  38:     0x7fffb53358fa - _pthread_start
thread 'main' panicked at 'rustc_thread failed: Any', src/libcore/result.rs:859
stack backtrace:
   0:        0x1140a10d3 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h34a7b169ac42b490
   1:        0x1140ae134 - std::panicking::default_hook::{{closure}}::hcc7f46907143dca1
   2:        0x1140add4c - std::panicking::default_hook::h9cd165f254d86e53
   3:        0x1140b0817 - std::panicking::rust_panic_with_hook::h2bd2f0b446f0face
   4:        0x1140b06b4 - std::panicking::begin_panic::h1732f61ecaaa434e
   5:        0x1140b0622 - std::panicking::begin_panic_fmt::h2948dd4668f99175
   6:        0x1140b0587 - rust_begin_unwind
   7:        0x1140ed750 - core::panicking::panic_fmt::hb2e726f3b579b19d
   8:        0x10e4493ef - core::result::unwrap_failed::ha3c8227ee586b3d0
   9:        0x10e44e618 - cargo_clippy::main::h9eccb98a94b003e5
  10:        0x1140b380a - __rust_maybe_catch_panic
  11:        0x1140b11a4 - std::rt::lang_start::h1cb64d2994eb2d7c
error: Could not compile `image`.

Caused by:
  process didn't exit successfully: `/Users/csteffen/.cargo/bin/cargo-clippy --crate-name image src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -Zno-trans --cfg feature="cargo-clippy" --cfg feature="png_codec" --cfg feature="tiff" --cfg feature="ico" --cfg feature="hdr" --cfg feature="default" --cfg feature="webp" --cfg feature="ppm" --cfg feature="png" --cfg feature="gif" --cfg feature="bmp" --cfg feature="scoped_threadpool" --cfg feature="tga" --cfg feature="gif_codec" --cfg feature="jpeg" --cfg feature="jpeg-decoder" -C metadata=1666c8fd62b5c4ee -C extra-filename=-1666c8fd62b5c4ee --out-dir /Users/csteffen/src/image/target/debug/deps -L dependency=/Users/csteffen/src/image/target/debug/deps --extern jpeg_decoder=/Users/csteffen/src/image/target/debug/deps/libjpeg_decoder-48b766e3b99e05bb.rlib --extern png=/Users/csteffen/src/image/target/debug/deps/libpng-891680363f77ff6c.rlib --extern num_iter=/Users/csteffen/src/image/target/debug/deps/libnum_iter-b399bbd189e5f67b.rlib --extern scoped_threadpool=/Users/csteffen/src/image/target/debug/deps/libscoped_threadpool-58ec7837165a2885.rlib --extern num_rational=/Users/csteffen/src/image/target/debug/deps/libnum_rational-10478f086e0c85c0.rlib --extern gif=/Users/csteffen/src/image/target/debug/deps/libgif-9741810a2aef6c61.rlib --extern enum_primitive=/Users/csteffen/src/image/target/debug/deps/libenum_primitive-426259b3f2e82106.rlib --extern num_traits=/Users/csteffen/src/image/target/debug/deps/libnum_traits-a8c1b7cdefa880e5.rlib --extern byteorder=/Users/csteffen/src/image/target/debug/deps/libbyteorder-190c8b8b4cb7f472.rlib` (exit code: 101)
```

**Comment by oli-obk** [comment]
This is originating from inside the compiler... I'll check what's going on...

**Comment by oli-obk** [comment]
Aaaand, of course [it's my fault](https://github.com/Manishearth/rust-clippy/pull/1305#discussion_r85660416)...

We need to do this properly.... but I'm not sure how :/ Until then, we could simply check whether the spans' ctxt differs and not produce a suggestion in that case.

**Comment by oli-obk** [comment]
Not reproducible anymore
