### ISSUE TITLE
mut_mut_macro test fails after 'cargo check': "multiple matching crates for `lazy_static`"

### ISSUE THREAD

**Issue by ykrivopalov** [rust-lang-nursery/rust-clippy#2139]
I have a problem with tests execution. Every time, when I do `cargo check`, subsequent launch of `cargo test` fails.

It reproduces like this:
```
cargo clean
cargo test # SUCCEED
cargo test # SUCCEED
cargo check
cargo test # FAILED
```

It worked in such a way for me with different releases.

My current environment:
```
$ rustup show
Default host: x86_64-unknown-linux-gnu

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.22.0-nightly (02a24dbdd 2017-10-13)
```

Failed test:
```
failures:

---- [run-pass] run-pass/mut_mut_macro.rs stdout ----

error: compilation failed!
status: exit code: 101
command: target/debug/clippy-driver tests/run-pass/mut_mut_macro.rs -L target/debug/test_build_base --target=x86_64-unknown-linux-gnu --error-format json -L target/debug/test_build_base/mut_mut_macro.stage-id.run-pass.libaux -C prefer-dynamic -o target/debug/test_build_base/mut_mut_macro.stage-id -L target/debug/ -L target/debug/deps -Dwarnings
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
{"message":"multiple matching crates for `lazy_static`","code":{"code":"E0464","explanation":null},"level":"error","spans":[{"file_name":"tests/run-pass/mut_mut_macro.rs","byte_start":74,"byte_end":99,"line_start":7,"line_end":7,"column_start":1,"column_end":26,"is_primary":true,"text":[{"text":"extern crate lazy_static;","highlight_start":1,"highlight_end":26}],"label":null,"suggested_replacement":null,"expansion":null}],"children":[{"message":"candidates:","code":null,"level":"note","spans":[],"children":[],"rendered":null},{"message":"path: /home/yk/dev/rust-clippy/target/debug/deps/liblazy_static-e94bdb055ffaade6.rlib","code":null,"level":"note","spans":[],"children":[],"rendered":null},{"message":"crate name: lazy_static","code":null,"level":"note","spans":[],"children":[],"rendered":null},{"message":"crate name: lazy_static","code":null,"level":"note","spans":[],"children":[],"rendered":null}],"rendered":null}
{"message":"can't find crate for `lazy_static`","code":{"code":"E0463","explanation":"\nA plugin/crate was declared but cannot be found. Erroneous code example:\n\n```compile_fail,E0463\n#![feature(plugin)]\n#![plugin(cookie_monster)] // error: can't find crate for `cookie_monster`\nextern crate cake_is_a_lie; // error: can't find crate for `cake_is_a_lie`\n```\n\nYou need to link your code to the relevant crate in order to be able to use it\n(through Cargo or the `-L` option of rustc example). Plugins are crates as\nwell, and you link to them the same way.\n"},"level":"error","spans":[{"file_name":"tests/run-pass/mut_mut_macro.rs","byte_start":74,"byte_end":99,"line_start":7,"line_end":7,"column_start":1,"column_end":26,"is_primary":true,"text":[{"text":"extern crate lazy_static;","highlight_start":1,"highlight_end":26}],"label":"can't find crate","suggested_replacement":null,"expansion":null}],"children":[],"rendered":null}
{"message":"aborting due to 2 previous errors","code":null,"level":"error","spans":[],"children":[],"rendered":null}
thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:525:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'rustc_thread failed: Any', /checkout/src/libcore/result.rs:906:4

------------------------------------------

thread '[run-pass] run-pass/mut_mut_macro.rs' panicked at 'explicit panic', /home/yk/.cargo/registry/src/github.com-1ecc6299db9ec823/compiletest_rs-0.2.10/src/runtest.rs:2374:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Full test log: https://hastebin.com/etekarumis

I don't understand why it happend. Does it reproduce for anybody else?

**Comment by oli-obk** [comment]
This is an issue with compiletest-rs. You need to do `cargo clean` when that happens.

**Comment by phansch** [comment]
I ran into the same problem yesterday. For me it seems to be caused by running [rls](https://github.com/rust-lang-nursery/rls) in the background through vim. When I disable it, everything works. I will try to find out a bit more later today. 

```
nightly-x86_64-unknown-linux-gnu (default)
rustc 1.23.0-nightly (45594d5de 2017-11-22)
```

**Comment by oli-obk** [comment]
Ugh, compiletest is such a mess. We should probably be including extern libraries explicitly like cargo does. I wonder if we can reuse some logic from cargo.
