### ISSUE TITLE
Ty::fn_sig() called on non-fn type

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/rust-clippy#2247]
```rust
pub fn retry<F: Fn()>(f: F) {
    for _i in 0.. {
        f();
    }
}

fn main() {}
```

```
error: internal compiler error: /checkout/src/librustc/ty/sty.rs:1488: Ty::fn_sig() called on non-fn type: F

thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:501:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'rustc_thread failed: Any', /checkout/src/libcore/result.rs:906:4
error: Could not compile `testing`.
```

- cargo clippy 0.0.174
- rustc 1.23.0-nightly (e97ba8328 2017-11-25)

**Comment by dtolnay** [comment]
<details><summary>Backtrace</summary>

```
thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:501:8
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
             at /checkout/src/libstd/sys_common/backtrace.rs:57
   2: _ZN3std9panicking12default_hook28_$u7b$$u7b$closure$u7d$$u7d$17haba1b8b7cf61bd7aE.llvm.526D1984
             at /checkout/src/libstd/panicking.rs:381
   3: _ZN3std9panicking12default_hook17h7be06c8634f460d7E.llvm.526D1984
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
   6: rustc_errors::Handler::bug
   7: <std::thread::local::LocalKey<T>>::with
   8: rustc::ty::context::tls::with_opt
   9: _ZN5rustc7session16opt_span_bug_fmt17hb56476d414c941fdE.llvm.1FD79818
  10: rustc::session::bug_fmt
  11: rustc::ty::sty::<impl rustc::ty::TyS<'tcx>>::fn_sig
  12: <clippy_lints::loops::VarVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  13: rustc::hir::intravisit::walk_expr
  14: clippy_lints::loops::check_for_loop
  15: <clippy_lints::loops::Pass as rustc::lint::LateLintPass<'a, 'tcx>>::check_expr
  16: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  17: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_local
  18: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_block
  19: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  20: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_block
  21: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  22: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_body
  23: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_nested_body
  24: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_fn
  25: rustc::hir::intravisit::walk_item
  26: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item
  27: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_mod
  28: rustc::hir::intravisit::walk_crate
  29: rustc::lint::context::check_crate
  30: <std::thread::local::LocalKey<T>>::with
  31: <std::thread::local::LocalKey<T>>::with
  32: rustc::ty::context::TyCtxt::create_and_enter
  33: rustc_driver::driver::compile_input
  34: rustc_driver::run_compiler
thread 'main' panicked at 'rustc_thread failed: Any', /checkout/src/libcore/result.rs:906:4
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
             at /checkout/src/libstd/sys_common/backtrace.rs:57
   2: _ZN3std9panicking12default_hook28_$u7b$$u7b$closure$u7d$$u7d$17haba1b8b7cf61bd7aE.llvm.526D1984
             at /checkout/src/libstd/panicking.rs:381
   3: _ZN3std9panicking12default_hook17h7be06c8634f460d7E.llvm.526D1984
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: _ZN3std9panicking11begin_panic17hb62cac1b1e3c5e79E.llvm.526D1984
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::result::unwrap_failed
  10: clippy_driver::main
  11: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:101
  12: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/rt.rs:58
  13: __libc_start_main
  14: _start
```

</details>

**Comment by o01eg** [comment]
Is it related to https://github.com/rust-lang/rust/issues/41880 ?

**Comment by dtolnay** [comment]
I don't think so, beyond that `fn_sig` is being called in both cases. The code that detects the buggy behavior may be the same but I expect the bug is different. Also the repro in that issue no longer crashes as of 1.23.0-nightly.
