### ISSUE TITLE
Out of bounds panic inside is_unit_expr lint

### ISSUE THREAD

**Issue by mateon1** [rust-lang-nursery/rust-clippy#2302]
While linting this function:
```rust
pub fn magic(x: u8) {
    let a = match x {
        b'A' => {},
    };
}
```
Clippy crashes with:
```gdb
   Compiling clippyrepro v0.1.0 (file:///shared/dev/clippyrepro)
thread 'rustc' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', /checkout/src/liballoc/vec.rs:1551:10
stack backtrace:
   0:     0x7ffff52cdc53 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::ha5b8e217200b2a6c
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x7ffff52c82fc - std::sys_common::backtrace::_print::hf967d7451821bfd9
                               at /checkout/src/libstd/sys_common/backtrace.rs:68
   2:     0x7ffff52db221 - std::panicking::default_hook::{{closure}}::hf74c8a8fa97e4f45
                               at /checkout/src/libstd/sys_common/backtrace.rs:57
                               at /checkout/src/libstd/panicking.rs:381
   3:     0x7ffff52daf85 - std::panicking::default_hook::h8397f0aa6c72620a
                               at /checkout/src/libstd/panicking.rs:397
   4:     0x7ffff52db6f4 - std::panicking::rust_panic_with_hook::h46b83fe16959f2e3
                               at /checkout/src/libstd/panicking.rs:577
   5:     0x7ffff52db58c - std::panicking::begin_panic::hfed38a370822b09c
                               at /checkout/src/libstd/panicking.rs:538
   6:     0x7ffff52db4a9 - std::panicking::begin_panic_fmt::h9d7776ab0e3efb40
                               at /checkout/src/libstd/panicking.rs:522
   7:     0x7ffff52db432 - rust_begin_unwind
                               at /checkout/src/libstd/panicking.rs:498
   8:     0x7ffff53317b0 - core::panicking::panic_fmt::hb79068ecc27c1709
                               at /checkout/src/libcore/panicking.rs:71
   9:     0x7ffff5331753 - core::panicking::panic_bounds_check::hd03530a32e2ea06c
                               at /checkout/src/libcore/panicking.rs:58
  10:     0x5555556a1513 - clippy_lints::is_unit_expr::is_unit_expr::hf4c9e83c1f5c2a08
  11:     0x5555556a14a2 - clippy_lints::is_unit_expr::is_unit_expr::hf4c9e83c1f5c2a08
  12:     0x5555556a1374 - <clippy_lints::is_unit_expr::UnitExpr as rustc::lint::EarlyLintPass>::check_stmt::he0f94cc25ecb3641
  13:     0x7ffff6a0f2cd - <rustc::lint::context::EarlyContext<'a> as syntax::visit::Visitor<'a>>::visit_stmt::he4c406d8df1ee149
  14:     0x7ffff6a10fde - <rustc::lint::context::EarlyContext<'a> as syntax::visit::Visitor<'a>>::visit_block::h33fd92131d6c57c8
  15:     0x7ffff6a0f67f - <rustc::lint::context::EarlyContext<'a> as syntax::visit::Visitor<'a>>::visit_fn::hdf7d8a4f2d55aebb
  16:     0x7ffff674a87f - syntax::visit::walk_item::hb8247034c60e050b
  17:     0x7ffff6a0e79e - <rustc::lint::context::EarlyContext<'a> as syntax::visit::Visitor<'a>>::visit_item::hed58ef24dd28de9b
  18:     0x7ffff6a1096f - <rustc::lint::context::EarlyContext<'a> as syntax::visit::Visitor<'a>>::visit_mod::h517ff3ac085d30c2
  19:     0x7ffff6a13424 - rustc::lint::context::check_ast_crate::hf128344a44fa3540
  20:     0x7ffff7a6ef55 - rustc_driver::driver::compile_input::hc6c21bfee871baf7
  21:     0x7ffff7ac67fa - rustc_driver::run_compiler::hadef00ab2585608d
  22:     0x5555555b3c36 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf047b2c9116498a1
  23:     0x5555555b433b - std::panicking::try::do_call::hfde8cf636776812b
  24:     0x7ffff52e59fe - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:99
  25:     0x5555555b9955 - <F as alloc::boxed::FnBox<A>>::call_box::ha323ac95962948bd
  26:     0x7ffff52da0ab - std::sys::imp::thread::Thread::new::thread_start::h093c7d28b855e3ae
                               at /checkout/src/liballoc/boxed.rs:772
                               at /checkout/src/libstd/sys_common/thread.rs:23
                               at /checkout/src/libstd/sys/unix/thread.rs:90
  27:     0x7ffff504b493 - start_thread
  28:     0x7ffff4874abe - __clone
  29:                0x0 - <unknown>
thread 'main' panicked at 'rustc_thread failed: Any', /checkout/src/libcore/result.rs:906:4
stack backtrace:
   0:     0x7ffff52cdc53 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::ha5b8e217200b2a6c
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x7ffff52c82fc - std::sys_common::backtrace::_print::hf967d7451821bfd9
                               at /checkout/src/libstd/sys_common/backtrace.rs:68
   2:     0x7ffff52db221 - std::panicking::default_hook::{{closure}}::hf74c8a8fa97e4f45
                               at /checkout/src/libstd/sys_common/backtrace.rs:57
                               at /checkout/src/libstd/panicking.rs:381
   3:     0x7ffff52daf85 - std::panicking::default_hook::h8397f0aa6c72620a
                               at /checkout/src/libstd/panicking.rs:397
   4:     0x7ffff52db6f4 - std::panicking::rust_panic_with_hook::h46b83fe16959f2e3
                               at /checkout/src/libstd/panicking.rs:577
   5:     0x7ffff52db58c - std::panicking::begin_panic::hfed38a370822b09c
                               at /checkout/src/libstd/panicking.rs:538
   6:     0x7ffff52db4a9 - std::panicking::begin_panic_fmt::h9d7776ab0e3efb40
                               at /checkout/src/libstd/panicking.rs:522
   7:     0x7ffff52db432 - rust_begin_unwind
                               at /checkout/src/libstd/panicking.rs:498
   8:     0x7ffff53317b0 - core::panicking::panic_fmt::hb79068ecc27c1709
                               at /checkout/src/libcore/panicking.rs:71
   9:     0x5555555b974a - core::result::unwrap_failed::h447f9f01a67781a8
  10:     0x5555555bb2af - clippy_driver::main::hc5927ed41fd66d22
  11:     0x7ffff52e59fe - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:99
  12:     0x7ffff52dbc8b - std::rt::lang_start::h314ab5124ccc3af1
                               at /checkout/src/libstd/panicking.rs:459
                               at /checkout/src/libstd/panic.rs:365
                               at /checkout/src/libstd/rt.rs:58
  13:     0x7ffff47ac2e0 - __libc_start_main
  14:     0x5555555b2429 - _start
  15:                0x0 - <unknown>
error: Could not compile `clippyrepro`.
```

**Comment by mateon1** [comment]
False alarm - duplicate of #2160, on an outdated `0.0.171` version of clippy.
