### ISSUE TITLE
Clippy crashes when encountering an empty match expression `match x {}`

### ISSUE THREAD

**Issue by mateon1** [rust-lang-nursery/rust-clippy#2303]
Using Clippy version `0.0.177` with `rustc 1.24.0-nightly (cddc4a62d 2017-12-26)`

When compiling the following code, clippy crashes
```rust
pub fn magic(x: u8) {
    match x {}
}
```

Stack trace:
```gdb
   Compiling clippyrepro v0.1.0 (file:///shared/dev/clippyrepro)
error[E0004]: non-exhaustive patterns: type u8 is non-empty
 --> src/lib.rs:2:11
  |
2 |     match x {}
  |           ^
  |
help: Please ensure that all possible cases are being handled; possibly adding wildcards or more match arms.
 --> src/lib.rs:2:11
  |
2 |     match x {}
  |           ^

error: aborting due to previous error

thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:537:8
stack backtrace:
   0:     0x7ffff50f55bb - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h8d76ba73dd14be2a
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x7ffff5104d0e - std::sys_common::backtrace::print::h555e442d6bd84484
                               at /checkout/src/libstd/sys_common/backtrace.rs:68
                               at /checkout/src/libstd/sys_common/backtrace.rs:57
   2:     0x7ffff50e1f20 - std::panicking::default_hook::{{closure}}::hb5b22f3b5941dfc2
                               at /checkout/src/libstd/panicking.rs:381
   3:     0x7ffff50e1a46 - std::panicking::default_hook::he8e905e7b379830b
                               at /checkout/src/libstd/panicking.rs:397
   4:     0x7ffff50e234b - std::panicking::rust_panic_with_hook::h2f97e99a7e8ad767
                               at /checkout/src/libstd/panicking.rs:577
   5:     0x7ffff585ff87 - std::panicking::begin_panic::hb264bf02335dd4dd
   6:     0x7ffff587eb30 - rustc_errors::Handler::abort_if_errors::h29df86dea1af8018
   7:     0x7ffff70a76dc - rustc_const_eval::check_match::check_crate::hfca4d175253712e3
   8:     0x7ffff7a9f16c - <std::thread::local::LocalKey<T>>::with::h41684bcbf7cf335f
   9:     0x7ffff7a9e946 - <std::thread::local::LocalKey<T>>::with::h2ef08ada98f77cc3
  10:     0x7ffff7b01608 - rustc::ty::context::TyCtxt::create_and_enter::h81ffbcdc28537323
  11:     0x7ffff7a50f0d - rustc_driver::driver::compile_input::hc963e46370ea6321
  12:     0x7ffff7ad4d01 - rustc_driver::run_compiler::hf5469fb113e83f17
  13:     0x5555555b5272 - std::sys_common::backtrace::__rust_begin_short_backtrace::hae35416a70120764
  14:     0x5555555bab7b - std::panicking::try::do_call::h9db5be123d145193
  15:     0x7ffff512ed7e - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:101
  16:     0x5555555ba82c - <F as alloc::boxed::FnBox<A>>::call_box::hf65c01e57cfc1df7
  17:     0x7ffff5108d6b - std::sys::unix::thread::Thread::new::thread_start::h23d8a4a5863d2e93
                               at /checkout/src/liballoc/boxed.rs:827
                               at /checkout/src/libstd/sys_common/thread.rs:24
                               at /checkout/src/libstd/sys/unix/thread.rs:90
  18:     0x7ffff4e82493 - start_thread
  19:     0x7ffff46ababe - __clone
  20:                0x0 - <unknown>
thread 'main' panicked at 'rustc_thread failed: Any', /checkout/src/libcore/result.rs:916:4
stack backtrace:
   0:     0x7ffff50f55bb - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h8d76ba73dd14be2a
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x7ffff5104d0e - std::sys_common::backtrace::print::h555e442d6bd84484
                               at /checkout/src/libstd/sys_common/backtrace.rs:68
                               at /checkout/src/libstd/sys_common/backtrace.rs:57
   2:     0x7ffff50e1f20 - std::panicking::default_hook::{{closure}}::hb5b22f3b5941dfc2
                               at /checkout/src/libstd/panicking.rs:381
   3:     0x7ffff50e1a46 - std::panicking::default_hook::he8e905e7b379830b
                               at /checkout/src/libstd/panicking.rs:397
   4:     0x7ffff50e234b - std::panicking::rust_panic_with_hook::h2f97e99a7e8ad767
                               at /checkout/src/libstd/panicking.rs:577
   5:     0x7ffff50e219e - std::panicking::begin_panic::h200f7bd7099dd5a7
                               at /checkout/src/libstd/panicking.rs:538
   6:     0x7ffff50e210a - std::panicking::begin_panic_fmt::h45cc7477b8f7371e
                               at /checkout/src/libstd/panicking.rs:522
   7:     0x7ffff50e20a2 - rust_begin_unwind
                               at /checkout/src/libstd/panicking.rs:498
   8:     0x7ffff5180430 - core::panicking::panic_fmt::h7adcb99411a5e200
                               at /checkout/src/libcore/panicking.rs:71
   9:     0x5555555bfdaf - core::result::unwrap_failed::hbb8a8902d29c13a2
  10:     0x5555555c2a46 - clippy_driver::main::hfb9ce10f3642c294
  11:     0x7ffff512ed7e - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:101
  12:     0x7ffff50f522f - std::rt::lang_start::h4e4a30f65f60cbe9
                               at /checkout/src/libstd/panicking.rs:459
                               at /checkout/src/libstd/panic.rs:365
                               at /checkout/src/libstd/rt.rs:58
  13:     0x7ffff45e32e0 - __libc_start_main
  14:     0x5555555b4309 - _start
  15:                0x0 - <unknown>
error: Could not compile `clippyrepro`.
```

This does not happen if `x` is the never type.
`cargo check` and `cargo build` correctly error on a non-exhaustive pattern match and don't crash.

**Comment by Manishearth** [comment]
Hmm, looks like something changed in rustc_driver. Usually it catches FatalError panics, and that's not happening the same way.
