### ISSUE TITLE
running tests in release mode depends on debug build

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang-nursery/rust-clippy#2383]
running 
e6428873cb0eba71e052d8a65708a69be97d17e1

The dogfood test apparently wrongly assumes that a debug build has been made at all times.
This breaks running ````cargo test --release```` in the clippy repo.

````
    Running target/release/deps/dogfood-70647cbfd0293c93

running 1 test
test dogfood ... FAILED

failures:

---- dogfood stdout ----
	status: exit code: 101
stdout: lib: clippy

stderr:     Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/cargo-clippy`
error: failed to run `rustc` to learn about target-specific information

Caused by:
  could not execute process `/home/matthias/vcs/github/rust-clippy/target/debug/clippy-driver rustc - --crate-name ___ --print=file-names -C target-cpu=native --target x86_64-unknown-linux-gnu --crate-type bin --crate-type dylib --crate-type proc-macro --crate-type rlib` (never executed)

Caused by:
  No such file or directory (os error 2)

thread 'dogfood' panicked at 'assertion failed: output.status.success()', tests/dogfood.rs:21:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:68
             at libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:390
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
   6: dogfood::dogfood
   7: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1441
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:817
   8: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102


failures:
    dogfood

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test dogfood'
````

**Comment by oli-obk** [comment]
I so hoped noone would notice :D

**Comment by oli-obk** [comment]
Wait a second... I fixed that a while ago... Something is fishy. Looking into it.

**Comment by oli-obk** [comment]
aha, found the culprit. If you have a clean repository, `cargo run --bin cargo-clippy` will *not* build `clippy-driver`, and thus fail when trying to call it

dogfood runs `cargo run --bin cargo-clippy`, which will fail because it's not passing the `--release` flag.

**Comment by matthiaskrgr** [comment]
Looks like the underlying issue has been fixed, closing.
