### ISSUE TITLE
Panic during check

### ISSUE THREAD

**Issue by cspiegel** [rust-lang-nursery/rust-clippy#2423]
rustc 1.25.0-nightly (8ccab7eed 2018-01-31) running on x86_64-unknown-linux-gnu
clippy 0.0.184

Given the following code:

```rust
fn main() {
    if true {
        f(&[0; 62]);
        f(&[0; 4]);
        f(&[0; 3]);
    } else {
        f(&[0; 126]);
        f(&[0; 6]);
        f(&[0; 6]);
    }
}

fn f(val: &[u8]) {
}
```

Running clippy results in:

```
error: internal compiler error: librustc/ty/context.rs:478: node_id_to_type: no type for node `expr 62 (id=11)`

thread 'rustc' panicked at 'Box<Any>', librustc_errors/lib.rs:529:9
stack backtrace:
   0:     0x7f07c1b4f57b - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hf340f1cc00c949f5
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x7f07c1b1aec0 - std::sys_common::backtrace::print::h010be6afe40dde29
                               at libstd/sys_common/backtrace.rs:71
                               at libstd/sys_common/backtrace.rs:59
   2:     0x7f07c1b21190 - std::panicking::default_hook::{{closure}}::h9fdbc7fb64bc0a68
                               at libstd/panicking.rs:380
   3:     0x7f07c1b20ee7 - std::panicking::default_hook::hd5afa9e2f124806d
                               at libstd/panicking.rs:396
   4:     0x7f07c1b215db - std::panicking::rust_panic_with_hook::h5b79089958c4d249
                               at libstd/panicking.rs:576
   5:     0x7f07c22999a7 - std::panicking::begin_panic::hbac0e30124226fd9
   6:     0x7f07c22ae9b1 - rustc_errors::Handler::bug::h4dca7312c2e520d6
   7:     0x7f07c32cd2df - <std::thread::local::LocalKey<T>>::with::haf7a235c17e632ce
   8:     0x7f07c31c6d8e - rustc::ty::context::tls::with_opt::h2c2243932021753d
   9:     0x7f07c34d0a27 - rustc::session::opt_span_bug_fmt::hb9693baf4a338c20
  10:     0x7f07c34d0936 - rustc::session::bug_fmt::hc1eda3f607192238
  11:     0x7f07c31c0525 - rustc::ty::context::TypeckTables::expr_ty::h0b7e17faf1edad82
  12:     0x55e0b394b32a - clippy_lints::consts::ConstEvalLateContext::expr::hf7239cb814cd047a
  13:     0x55e0b395e12f - clippy_lints::utils::hir_utils::SpanlessEq::eq_expr::h9c98718aa9ef3763
  14:     0x55e0b395ee04 - clippy_lints::utils::hir_utils::SpanlessEq::eq_expr::h9c98718aa9ef3763
  15:     0x55e0b395ee04 - clippy_lints::utils::hir_utils::SpanlessEq::eq_expr::h9c98718aa9ef3763
  16:     0x55e0b395e562 - clippy_lints::utils::hir_utils::SpanlessEq::eq_expr::h9c98718aa9ef3763
  17:     0x55e0b3a94859 - <clippy_lints::copies::CopyAndPaste as rustc::lint::LateLintPass<'a, 'tcx>>::check_expr::hb8ad779219b714a7
  18:     0x7f07c3441b00 - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr::hb1cfad14094e5b76
  19:     0x7f07c3443ae5 - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_block::hfb8a4de625c3590f
  20:     0x7f07c3441ba8 - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr::hb1cfad14094e5b76
  21:     0x7f07c3440b20 - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_body::hd3e095cc9d24ba52
  22:     0x7f07c344099a - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_nested_body::h05a0f294eb7e5b95
  23:     0x7f07c34422cc - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_fn::hd6389d3e0def5b47
  24:     0x7f07c32832ec - rustc::hir::intravisit::walk_item::hb01537a145c911b3
  25:     0x7f07c34410ae - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item::h18dee8860a903102
  26:     0x7f07c34434dc - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_mod::hc7982cc23f7a1eaa
  27:     0x7f07c32771bc - rustc::hir::intravisit::walk_crate::hbd808bc6c5d630b2
  28:     0x7f07c344979f - rustc::lint::context::check_crate::h7fbcc450751a145e
  29:     0x7f07c446ac53 - <std::thread::local::LocalKey<T>>::with::h35950e9ae5d5c0ef
  30:     0x7f07c4470a23 - <std::thread::local::LocalKey<T>>::with::hca4e7a50f83a692d
  31:     0x7f07c44c5138 - rustc::ty::context::TyCtxt::create_and_enter::h49d3e95928389864
  32:     0x7f07c43d93de - rustc_driver::driver::compile_input::h86e312088c9311fc
  33:     0x7f07c44a1218 - rustc_driver::run_compiler::hb9c89309beedfa55
  34:     0x55e0b3916f12 - std::sys_common::backtrace::__rust_begin_short_backtrace::h92e4e6acf1a4f98e
  35:     0x55e0b39172cb - std::panicking::try::do_call::h2941d3c167e958dc
  36:     0x7f07c1b640ae - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:102
  37:     0x55e0b391a93d - <F as alloc::boxed::FnBox<A>>::call_box::hd3f972c4d1343bd2
  38:     0x7f07c1b53477 - std::sys_common::thread::start_thread::hb176f2ed2201bf7e
                               at /checkout/src/liballoc/boxed.rs:798
                               at libstd/sys_common/thread.rs:24
  39:     0x7f07c1b21ee8 - std::sys::unix::thread::Thread::new::thread_start::hc30d7b5fed49aff0
                               at libstd/sys/unix/thread.rs:90
  40:     0x7f07c18b73d4 - start_thread
                               at /tmp/ports/port.20171112-5930-k83r29/glibc-2.26/nptl/pthread_create.c:465
  41:     0x7f07c13d9e6e - __clone
                               at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  42:                0x0 - <unknown>
```

**Comment by oli-obk** [comment]
Don't have time to fix this today, but if somebody wants to take it:

the issue is that `ExprRepeat` in `hir_utils` in `eq_expr` takes the expression via `tcx.hir.body(id)`, but doesn't take the `body_tables` and `param_env` from the constant but from its surrounding body.

Instead of getting the expression and feeding it to `constant` we should be creating a `ConstEvalLateContext` directly and evaluating it with the correct tables and environment.
