### ISSUE TITLE
GitHub Pages for v0.0.191 does not exist

### ISSUE THREAD

**Issue by ordovicia** [rust-lang-nursery/rust-clippy#2600]
https://rust-lang-nursery.github.io/rust-clippy/v0.0.191/index.html does not exist.

**Comment by oli-obk** [comment]
I fail at python, badly:

```
Traceback (most recent call last):
  File "./util/export.py", line 69, in <module>
    main()
  File "./util/export.py", line 54, in main
    lintlist, configs = parse_all()
  File "/home/travis/build/rust-lang-nursery/rust-clippy/util/lintlib.py", line 113, in parse_all
    parse_lints(lints, os.path.join(path, filename))
  File "/home/travis/build/rust-lang-nursery/rust-clippy/util/lintlib.py", line 83, in parse_lints
    line = next(fp)
```

**Comment by oli-obk** [comment]
why is that not breaking our build!?
