### ISSUE TITLE
Panic in clippy_lints::utils::higher::range

### ISSUE THREAD

**Issue by adam-rhebo** [rust-lang-nursery/rust-clippy#2727]
Clippy `0.0.196` seems to panic when compiling futures `0.1.21` using rustc `1.27.0-nightly (e82261dfb 2018-05-03)`:
```
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', /home/adam/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.196/src/utils/higher.rs:76:32
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:467
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:350
   7: rust_begin_unwind
             at libstd/panicking.rs:328
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::panicking::panic_bounds_check
             at libcore/panicking.rs:58
  10: clippy_lints::utils::higher::range
  11: <clippy_lints::ranges::Pass as rustc::lint::LateLintPass<'a, 'tcx>>::check_expr
  12: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  13: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_block
  14: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  15: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_body
  16: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_nested_body
  17: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_fn
  18: rustc::hir::intravisit::walk_impl_item
  19: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_impl_item
  20: rustc::hir::intravisit::walk_impl_item_ref
  21: rustc::hir::intravisit::walk_item
  22: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item
  23: rustc::hir::intravisit::walk_mod
  24: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_mod
  25: rustc::hir::intravisit::walk_item
  26: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item
  27: rustc::hir::intravisit::walk_mod
  28: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_mod
  29: rustc::hir::intravisit::walk_item
  30: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item
  31: rustc::hir::intravisit::walk_mod
  32: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_mod
  33: rustc::lint::context::check_crate
  34: rustc::ty::context::tls::enter_context
  35: <std::thread::local::LocalKey<T>>::with
  36: rustc::ty::context::TyCtxt::create_and_enter
  37: rustc_driver::driver::compile_input
  38: rustc_driver::run_compiler_impl
  39: <scoped_tls::ScopedKey<T>>::set
  40: syntax::with_globals
  41: rustc_driver::run_compiler
  42: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  43: std::panicking::try::do_call
  44: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  45: rustc_driver::run
  46: clippy_driver::main
  47: std::rt::lang_start::{{closure}}
  48: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  49: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  50: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  51: main
  52: __libc_start_main
  53: _start
query stack during panic:
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.27.0-nightly (e82261dfb 2018-05-03) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `futures`.
```

**Comment by oli-obk** [comment]
https://github.com/rust-lang-nursery/rust-clippy/blob/master/clippy_lints/src/utils/higher.rs#L76

curious. How can that function have only a single argument?

**Comment by adamreichold** [comment]
Ignore the above, I messed up the versions: This indeed reproducible when checking just `futures-rs`, but version `0.1.21` instead of `0.1.12`...

**Comment by adamreichold** [comment]
If I did this right, Clippy starts to fail with the `future-rs` commit [8fb28bca5936df73180bc071cf748ad0598adb37](https://github.com/rust-lang-nursery/futures-rs/commit/8fb28bca5936df73180bc071cf748ad0598adb37).

**Comment by dtolnay** [comment]
Minimized from Syn, which hits the same bug.

```rust
pub fn f(new: fn()) {
    new();
}
```

```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0',
clippy_lints/src/utils/higher.rs:75:34

  10: clippy_lints::utils::higher::range
             at clippy_lints/src/utils/higher.rs:75
  11: <clippy_lints::ranges::Pass as rustc::lint::LateLintPass<'a, 'tcx>>::check_expr
             at clippy_lints/src/ranges.rs:135
```

**Comment by oli-obk** [comment]
Oh... apparently our path matching code doesn't do a full match
