### ISSUE TITLE
Cannot compile clippy_lints v0.0.196 with latest nightly

### ISSUE THREAD

**Issue by l0b0** [rust-lang-nursery/rust-clippy#2731]
From [last build](https://travis-ci.org/l0b0/cronlist/jobs/375760645):

```
   Compiling clippy_lints v0.0.196
error[E0053]: method `consume` has an incompatible type for trait
  --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.196/src/escape.rs:89:5
   |
89 |     fn consume(&mut self, _: NodeId, _: Span, cmt: cmt<'tcx>, mode: ConsumeMode) {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected reference, found struct `std::rc::Rc`
   |
   = note: expected type `fn(&mut escape::EscapeDelegate<'a, 'tcx>, syntax::ast::NodeId, syntax_pos::Span, &rustc::middle::mem_categorization::cmt_<'tcx>, rustc::middle::expr_use_visitor::ConsumeMode)`
              found type `fn(&mut escape::EscapeDelegate<'a, 'tcx>, syntax::ast::NodeId, syntax_pos::Span, std::rc::Rc<rustc::middle::mem_categorization::cmt_<'tcx>>, rustc::middle::expr_use_visitor::ConsumeMode)`
error[E0053]: method `matched_pat` has an incompatible type for trait
  --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.196/src/escape.rs:97:5
   |
97 |     fn matched_pat(&mut self, _: &Pat, _: cmt<'tcx>, _: MatchMode) {}
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected reference, found struct `std::rc::Rc`
   |
   = note: expected type `fn(&mut escape::EscapeDelegate<'a, 'tcx>, &rustc::hir::Pat, &rustc::middle::mem_categorization::cmt_<'tcx>, rustc::middle::expr_use_visitor::MatchMode)`
              found type `fn(&mut escape::EscapeDelegate<'a, 'tcx>, &rustc::hir::Pat, std::rc::Rc<rustc::middle::mem_categorization::cmt_<'tcx>>, rustc::middle::expr_use_visitor::MatchMode)`
error[E0053]: method `consume_pat` has an incompatible type for trait
  --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.196/src/escape.rs:98:5
   |
98 |     fn consume_pat(&mut self, consume_pat: &Pat, cmt: cmt<'tcx>, _: ConsumeMode) {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected reference, found struct `std::rc::Rc`
   |
   = note: expected type `fn(&mut escape::EscapeDelegate<'a, 'tcx>, &rustc::hir::Pat, &rustc::middle::mem_categorization::cmt_<'tcx>, rustc::middle::expr_use_visitor::ConsumeMode)`
              found type `fn(&mut escape::EscapeDelegate<'a, 'tcx>, &rustc::hir::Pat, std::rc::Rc<rustc::middle::mem_categorization::cmt_<'tcx>>, rustc::middle::expr_use_visitor::ConsumeMode)`
error[E0053]: method `borrow` has an incompatible type for trait
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.196/src/escape.rs:138:5
    |
138 |     fn borrow(&mut self, _: NodeId, _: Span, cmt: cmt<'tcx>, _: ty::Region, _: ty::BorrowKind, loan_cause: LoanCause) {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected reference, found struct `std::rc::Rc`
    |
    = note: expected type `fn(&mut escape::EscapeDelegate<'a, 'tcx>, syntax::ast::NodeId, syntax_pos::Span, &rustc::middle::mem_categorization::cmt_<'tcx>, &'tcx rustc::ty::RegionKind, rustc::ty::BorrowKind, rustc::middle::expr_use_visitor::LoanCause)`
               found type `fn(&mut escape::EscapeDelegate<'a, 'tcx>, syntax::ast::NodeId, syntax_pos::Span, std::rc::Rc<rustc::middle::mem_categorization::cmt_<'tcx>>, &rustc::ty::RegionKind, rustc::ty::BorrowKind, rustc::middle::expr_use_visitor::LoanCause)`
error[E0053]: method `mutate` has an incompatible type for trait
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.196/src/escape.rs:160:5
    |
160 |     fn mutate(&mut self, _: NodeId, _: Span, _: cmt<'tcx>, _: MutateMode) {}
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected reference, found struct `std::rc::Rc`
    |
    = note: expected type `fn(&mut escape::EscapeDelegate<'a, 'tcx>, syntax::ast::NodeId, syntax_pos::Span, &rustc::middle::mem_categorization::cmt_<'tcx>, rustc::middle::expr_use_visitor::MutateMode)`
               found type `fn(&mut escape::EscapeDelegate<'a, 'tcx>, syntax::ast::NodeId, syntax_pos::Span, std::rc::Rc<rustc::middle::mem_categorization::cmt_<'tcx>>, rustc::middle::expr_use_visitor::MutateMode)`
error[E0053]: method `consume` has an incompatible type for trait
    --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.196/src/loops.rs:1415:5
     |
1415 |     fn consume(&mut self, _: NodeId, _: Span, _: cmt<'tcx>, _: ConsumeMode) {}
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected reference, found struct `std::rc::Rc`
     |
     = note: expected type `fn(&mut loops::MutatePairDelegate, syntax::ast::NodeId, syntax_pos::Span, &rustc::middle::mem_categorization::cmt_<'tcx>, rustc::middle::expr_use_visitor::ConsumeMode)`
                found type `fn(&mut loops::MutatePairDelegate, syntax::ast::NodeId, syntax_pos::Span, std::rc::Rc<rustc::middle::mem_categorization::cmt_<'tcx>>, rustc::middle::expr_use_visitor::ConsumeMode)`
error[E0053]: method `matched_pat` has an incompatible type for trait
    --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.196/src/loops.rs:1417:5
     |
1417 |     fn matched_pat(&mut self, _: &Pat, _: cmt<'tcx>, _: MatchMode) {}
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected reference, found struct `std::rc::Rc`
     |
     = note: expected type `fn(&mut loops::MutatePairDelegate, &rustc::hir::Pat, &rustc::middle::mem_categorization::cmt_<'tcx>, rustc::middle::expr_use_visitor::MatchMode)`
                found type `fn(&mut loops::MutatePairDelegate, &rustc::hir::Pat, std::rc::Rc<rustc::middle::mem_categorization::cmt_<'tcx>>, rustc::middle::expr_use_visitor::MatchMode)`
error[E0053]: method `consume_pat` has an incompatible type for trait
    --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.196/src/loops.rs:1419:5
     |
1419 |     fn consume_pat(&mut self, _: &Pat, _: cmt<'tcx>, _: ConsumeMode) {}
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected reference, found struct `std::rc::Rc`
     |
     = note: expected type `fn(&mut loops::MutatePairDelegate, &rustc::hir::Pat, &rustc::middle::mem_categorization::cmt_<'tcx>, rustc::middle::expr_use_visitor::ConsumeMode)`
                found type `fn(&mut loops::MutatePairDelegate, &rustc::hir::Pat, std::rc::Rc<rustc::middle::mem_categorization::cmt_<'tcx>>, rustc::middle::expr_use_visitor::ConsumeMode)`
error[E0053]: method `borrow` has an incompatible type for trait
    --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.196/src/loops.rs:1421:5
     |
1421 |     fn borrow(&mut self, _: NodeId, sp: Span, cmt: cmt<'tcx>, _: ty::Region, bk: ty::BorrowKind, _: LoanCause) {
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected reference, found struct `std::rc::Rc`
     |
     = note: expected type `fn(&mut loops::MutatePairDelegate, syntax::ast::NodeId, syntax_pos::Span, &rustc::middle::mem_categorization::cmt_<'tcx>, &'tcx rustc::ty::RegionKind, rustc::ty::BorrowKind, rustc::middle::expr_use_visitor::LoanCause)`
                found type `fn(&mut loops::MutatePairDelegate, syntax::ast::NodeId, syntax_pos::Span, std::rc::Rc<rustc::middle::mem_categorization::cmt_<'tcx>>, &rustc::ty::RegionKind, rustc::ty::BorrowKind, rustc::middle::expr_use_visitor::LoanCause)`
error[E0053]: method `mutate` has an incompatible type for trait
    --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.196/src/loops.rs:1434:5
     |
1434 |     fn mutate(&mut self, _: NodeId, sp: Span, cmt: cmt<'tcx>, _: MutateMode) {
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected reference, found struct `std::rc::Rc`
     |
     = note: expected type `fn(&mut loops::MutatePairDelegate, syntax::ast::NodeId, syntax_pos::Span, &rustc::middle::mem_categorization::cmt_<'tcx>, rustc::middle::expr_use_visitor::MutateMode)`
                found type `fn(&mut loops::MutatePairDelegate, syntax::ast::NodeId, syntax_pos::Span, std::rc::Rc<rustc::middle::mem_categorization::cmt_<'tcx>>, rustc::middle::expr_use_visitor::MutateMode)`
error[E0053]: method `consume` has an incompatible type for trait
    --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.196/src/loops.rs:2258:5
     |
2258 |     fn consume(&mut self, _: NodeId, _: Span, _: cmt<'tcx>, _: ConsumeMode) {}
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected reference, found struct `std::rc::Rc`
     |
     = note: expected type `fn(&mut loops::MutVarsDelegate, syntax::ast::NodeId, syntax_pos::Span, &rustc::middle::mem_categorization::cmt_<'tcx>, rustc::middle::expr_use_visitor::ConsumeMode)`
                found type `fn(&mut loops::MutVarsDelegate, syntax::ast::NodeId, syntax_pos::Span, std::rc::Rc<rustc::middle::mem_categorization::cmt_<'tcx>>, rustc::middle::expr_use_visitor::ConsumeMode)`
error[E0053]: method `matched_pat` has an incompatible type for trait
    --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.196/src/loops.rs:2260:5
     |
2260 |     fn matched_pat(&mut self, _: &Pat, _: cmt<'tcx>, _: MatchMode) {}
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected reference, found struct `std::rc::Rc`
     |
     = note: expected type `fn(&mut loops::MutVarsDelegate, &rustc::hir::Pat, &rustc::middle::mem_categorization::cmt_<'tcx>, rustc::middle::expr_use_visitor::MatchMode)`
                found type `fn(&mut loops::MutVarsDelegate, &rustc::hir::Pat, std::rc::Rc<rustc::middle::mem_categorization::cmt_<'tcx>>, rustc::middle::expr_use_visitor::MatchMode)`
error[E0053]: method `consume_pat` has an incompatible type for trait
    --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.196/src/loops.rs:2262:5
     |
2262 |     fn consume_pat(&mut self, _: &Pat, _: cmt<'tcx>, _: ConsumeMode) {}
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected reference, found struct `std::rc::Rc`
     |
     = note: expected type `fn(&mut loops::MutVarsDelegate, &rustc::hir::Pat, &rustc::middle::mem_categorization::cmt_<'tcx>, rustc::middle::expr_use_visitor::ConsumeMode)`
                found type `fn(&mut loops::MutVarsDelegate, &rustc::hir::Pat, std::rc::Rc<rustc::middle::mem_categorization::cmt_<'tcx>>, rustc::middle::expr_use_visitor::ConsumeMode)`
error[E0053]: method `borrow` has an incompatible type for trait
    --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.196/src/loops.rs:2264:5
     |
2264 |     fn borrow(&mut self, _: NodeId, _: Span, cmt: cmt<'tcx>, _: ty::Region, bk: ty::BorrowKind, _: LoanCause) {
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected reference, found struct `std::rc::Rc`
     |
     = note: expected type `fn(&mut loops::MutVarsDelegate, syntax::ast::NodeId, syntax_pos::Span, &rustc::middle::mem_categorization::cmt_<'tcx>, &'tcx rustc::ty::RegionKind, rustc::ty::BorrowKind, rustc::middle::expr_use_visitor::LoanCause)`
                found type `fn(&mut loops::MutVarsDelegate, syntax::ast::NodeId, syntax_pos::Span, std::rc::Rc<rustc::middle::mem_categorization::cmt_<'tcx>>, &rustc::ty::RegionKind, rustc::ty::BorrowKind, rustc::middle::expr_use_visitor::LoanCause)`
error[E0053]: method `mutate` has an incompatible type for trait
    --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.196/src/loops.rs:2270:5
     |
2270 |     fn mutate(&mut self, _: NodeId, _: Span, cmt: cmt<'tcx>, _: MutateMode) {
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected reference, found struct `std::rc::Rc`
     |
     = note: expected type `fn(&mut loops::MutVarsDelegate, syntax::ast::NodeId, syntax_pos::Span, &rustc::middle::mem_categorization::cmt_<'tcx>, rustc::middle::expr_use_visitor::MutateMode)`
                found type `fn(&mut loops::MutVarsDelegate, syntax::ast::NodeId, syntax_pos::Span, std::rc::Rc<rustc::middle::mem_categorization::cmt_<'tcx>>, rustc::middle::expr_use_visitor::MutateMode)`
error[E0053]: method `consume` has an incompatible type for trait
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.196/src/needless_pass_by_value.rs:370:5
    |
370 |     fn consume(&mut self, consume_id: NodeId, consume_span: Span, cmt: mc::cmt<'tcx>, mode: euv::ConsumeMode) {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected reference, found struct `std::rc::Rc`
    |
    = note: expected type `fn(&mut needless_pass_by_value::MovedVariablesCtxt<'a, 'tcx>, syntax::ast::NodeId, syntax_pos::Span, &rustc::middle::mem_categorization::cmt_<'tcx>, rustc::middle::expr_use_visitor::ConsumeMode)`
               found type `fn(&mut needless_pass_by_value::MovedVariablesCtxt<'a, 'tcx>, syntax::ast::NodeId, syntax_pos::Span, std::rc::Rc<rustc::middle::mem_categorization::cmt_<'tcx>>, rustc::middle::expr_use_visitor::ConsumeMode)`
error[E0053]: method `matched_pat` has an incompatible type for trait
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.196/src/needless_pass_by_value.rs:376:5
    |
376 |     fn matched_pat(&mut self, matched_pat: &Pat, cmt: mc::cmt<'tcx>, mode: euv::MatchMode) {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected reference, found struct `std::rc::Rc`
    |
    = note: expected type `fn(&mut needless_pass_by_value::MovedVariablesCtxt<'a, 'tcx>, &rustc::hir::Pat, &rustc::middle::mem_categorization::cmt_<'tcx>, rustc::middle::expr_use_visitor::MatchMode)`
               found type `fn(&mut needless_pass_by_value::MovedVariablesCtxt<'a, 'tcx>, &rustc::hir::Pat, std::rc::Rc<rustc::middle::mem_categorization::cmt_<'tcx>>, rustc::middle::expr_use_visitor::MatchMode)`
error[E0053]: method `consume_pat` has an incompatible type for trait
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.196/src/needless_pass_by_value.rs:384:5
    |
384 |     fn consume_pat(&mut self, consume_pat: &Pat, cmt: mc::cmt<'tcx>, mode: euv::ConsumeMode) {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected reference, found struct `std::rc::Rc`
    |
    = note: expected type `fn(&mut needless_pass_by_value::MovedVariablesCtxt<'a, 'tcx>, &rustc::hir::Pat, &rustc::middle::mem_categorization::cmt_<'tcx>, rustc::middle::expr_use_visitor::ConsumeMode)`
               found type `fn(&mut needless_pass_by_value::MovedVariablesCtxt<'a, 'tcx>, &rustc::hir::Pat, std::rc::Rc<rustc::middle::mem_categorization::cmt_<'tcx>>, rustc::middle::expr_use_visitor::ConsumeMode)`
error[E0053]: method `borrow` has an incompatible type for trait
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.196/src/needless_pass_by_value.rs:390:5
    |
390 |     fn borrow(&mut self, _: NodeId, _: Span, _: mc::cmt<'tcx>, _: ty::Region, _: ty::BorrowKind, _: euv::LoanCause) {}
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected reference, found struct `std::rc::Rc`
    |
    = note: expected type `fn(&mut needless_pass_by_value::MovedVariablesCtxt<'a, 'tcx>, syntax::ast::NodeId, syntax_pos::Span, &rustc::middle::mem_categorization::cmt_<'tcx>, &'tcx rustc::ty::RegionKind, rustc::ty::BorrowKind, rustc::middle::expr_use_visitor::LoanCause)`
               found type `fn(&mut needless_pass_by_value::MovedVariablesCtxt<'a, 'tcx>, syntax::ast::NodeId, syntax_pos::Span, std::rc::Rc<rustc::middle::mem_categorization::cmt_<'tcx>>, &rustc::ty::RegionKind, rustc::ty::BorrowKind, rustc::middle::expr_use_visitor::LoanCause)`
error[E0053]: method `mutate` has an incompatible type for trait
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.196/src/needless_pass_by_value.rs:392:5
    |
392 |     fn mutate(&mut self, _: NodeId, _: Span, _: mc::cmt<'tcx>, _: euv::MutateMode) {}
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected reference, found struct `std::rc::Rc`
    |
    = note: expected type `fn(&mut needless_pass_by_value::MovedVariablesCtxt<'a, 'tcx>, syntax::ast::NodeId, syntax_pos::Span, &rustc::middle::mem_categorization::cmt_<'tcx>, rustc::middle::expr_use_visitor::MutateMode)`
               found type `fn(&mut needless_pass_by_value::MovedVariablesCtxt<'a, 'tcx>, syntax::ast::NodeId, syntax_pos::Span, std::rc::Rc<rustc::middle::mem_categorization::cmt_<'tcx>>, rustc::middle::expr_use_visitor::MutateMode)`
error: aborting due to 20 previous errors
For more information about this error, try `rustc --explain E0053`.
```

**Comment by oli-obk** [comment]
Already fixed on master. I'll publish later today

**Comment by oli-obk** [comment]
0.0.197 is out

**Comment by otavio** [comment]
It stills fails but now seems to be a compiler bug:

```
    Checking openssl v0.10.7
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', clippy_lints/src/utils/higher.rs:76:32
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:467
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:350
   7: rust_begin_unwind
             at libstd/panicking.rs:328
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::panicking::panic_bounds_check
             at libcore/panicking.rs:58
  10: clippy_lints::utils::higher::range
  11: <clippy_lints::ranges::Pass as rustc::lint::LateLintPass<'a, 'tcx>>::check_expr
  12: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  13: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_block
  14: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  15: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_body
  16: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_nested_body
  17: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_fn
  18: rustc::hir::intravisit::walk_impl_item
  19: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_impl_item
  20: rustc::hir::intravisit::walk_impl_item_ref
  21: rustc::hir::intravisit::walk_item
  22: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item
  23: rustc::hir::intravisit::walk_mod
  24: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_mod
  25: rustc::hir::intravisit::walk_item
  26: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item
  27: rustc::hir::intravisit::walk_mod
  28: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_mod
  29: rustc::hir::intravisit::walk_item
  30: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item
  31: rustc::hir::intravisit::walk_mod
  32: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_mod
  33: rustc::lint::context::check_crate
  34: rustc::ty::context::tls::enter_context
  35: <std::thread::local::LocalKey<T>>::with
  36: rustc::ty::context::TyCtxt::create_and_enter
  37: rustc_driver::driver::compile_input
  38: rustc_driver::run_compiler_impl
  39: <scoped_tls::ScopedKey<T>>::set
  40: syntax::with_globals
  41: rustc_driver::run_compiler
  42: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  43: std::panicking::try::do_call
  44: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  45: rustc_driver::run
  46: clippy_driver::main
  47: std::rt::lang_start::{{closure}}
  48: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  49: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  50: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  51: main
  52: __libc_start_main
  53: _start
query stack during panic:
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.27.0-nightly (428ea5f6b 2018-05-06) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `futures`.
warning: build failed, waiting for other jobs to finish...
```

**Comment by oli-obk** [comment]
That's a runtime error tracked in #2727

I'm fixing it at the moment

Workaround: Use `cargo check` before `cargo clippy` to get the dependencies built

**Comment by otavio** [comment]
@oli-obk thanks for the prompt response. It does workaround it :+1:
