### ISSUE TITLE
ICE on kbknapp/clap-rs: 'main' panicked at 'byte index 50 is out of bounds 

### ISSUE THREAD

**Issue by zayenz** [rust-lang-nursery/rust-clippy#2812]
Running clippy on clap commit 3b633e68 (v3-master branch) results in an internal compiler error with the message 

    thread 'main' panicked at 'byte index 50 is out of bounds of `                static ONCE: Once = ONCE_INIT;`', libcore/str/mod.rs:2125:9

Nightly version: nightly-x86_64-apple-darwin rustc 1.28.0-nightly (990d8aa74 2018-05-25)
Clippy version: 0.0.205
Code that triggers the error: https://github.com/kbknapp/clap-rs/tree/v3-master at commit 3b633e68b16645f1f79e1856bab7adcc522b952e

Full backtrace
```
thread 'main' panicked at 'byte index 50 is out of bounds of `                static ONCE: Once = ONCE_INIT;`', libcore/str/mod.rs:2125:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::begin_panic_fmt
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::str::slice_error_fail
  10: core::str::traits::<impl core::slice::SliceIndex<str> for core::ops::range::RangeTo<usize>>::index::{{closure}}
  11: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once
  12: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  13: <rustc_errors::emitter::EmitterWriter as rustc_errors::emitter::Emitter>::emit
  14: rustc_errors::Handler::emit_db
  15: rustc_errors::diagnostic_builder::DiagnosticBuilder::emit
  16: clippy_lints::utils::span_lint_and_then
  17: <clippy_lints::eq_op::EqOp as rustc::lint::LateLintPass<'a, 'tcx>>::check_expr
  18: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  19: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_body
  20: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_nested_body
  21: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_fn
  22: rustc::hir::intravisit::walk_expr
  23: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  24: rustc::hir::intravisit::walk_expr
  25: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  26: rustc::hir::intravisit::walk_expr
  27: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  28: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_local
  29: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_block
  30: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  31: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_arm
  32: rustc::hir::intravisit::walk_expr
  33: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  34: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_block
  35: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  36: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  37: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_block
  38: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  39: rustc::hir::intravisit::walk_expr
  40: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  41: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_block
  42: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  43: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_arm
  44: rustc::hir::intravisit::walk_expr
  45: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  46: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_block
  47: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  48: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_block
  49: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  50: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_body
  51: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_nested_body
  52: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_fn
  53: rustc::hir::intravisit::walk_impl_item
  54: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_impl_item
  55: rustc::hir::intravisit::walk_impl_item_ref
  56: rustc::hir::intravisit::walk_item
  57: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item
  58: rustc::hir::intravisit::walk_mod
  59: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_mod
  60: rustc::hir::intravisit::walk_item
  61: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item
  62: rustc::hir::intravisit::walk_mod
  63: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_mod
  64: rustc::hir::intravisit::walk_item
  65: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item
  66: rustc::hir::intravisit::walk_mod
  67: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_mod
  68: rustc::lint::context::check_crate
  69: rustc::util::common::time
  70: rustc::ty::context::tls::enter_context
  71: <std::thread::local::LocalKey<T>>::with
  72: rustc::ty::context::TyCtxt::create_and_enter
  73: rustc_driver::driver::compile_input
  74: rustc_driver::run_compiler_with_pool
  75: syntax::with_globals
  76: rustc_driver::run_compiler
  77: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  78: std::panicking::try::do_call
  79: __rust_maybe_catch_panic
  80: rustc_driver::run
  81: clippy_driver::main
  82: std::rt::lang_start::{{closure}}
  83: std::panicking::try::do_call
  84: __rust_maybe_catch_panic
  85: std::rt::lang_start_internal
  86: main
query stack during panic:
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.28.0-nightly (990d8aa74 2018-05-25) running on x86_64-apple-darwin

note: compiler flags: -C codegen-units=4 -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `clap`.

To learn more, run the command again with --verbose.
```

**Comment by zayenz** [comment]
I am working on trying to reduce the amount of code needed to triggger the error.

**Comment by zayenz** [comment]
Unfortunately I could not manage to reduce the code in any significant way. In particular, changing any code before the line complained about changed the span that was out of bounds, so it seems to be a more global problem of spans than just the specific code here.
