### ISSUE TITLE
crashes checking cargo tests

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang-nursery/rust-clippy#2965]
rustc -V ````rustc 1.29.0-nightly (6a1c0637c 2018-07-23)````
cargo clippy -- -V ````0.0.212````
````
git clone https://github.com/rust-lang/cargo
cd cargo
git checkout db48c63b3641a29a20b572ed516c58c84450e3bd
sed -i '1d' tests/testsuite/main.rs  #remove deny(warnings)
RUST_BACKTRACE=1 cargo clippy  --all-targets --all-features
````
=>
````
[bunch of warnings]
warning: single-character string constant used as pattern
   --> tests/testsuite/support/mod.rs:788:49
    |
788 |                 .filter(|line| line.starts_with("{"))
    |                                -----------------^^^- help: try using a char instead: `line.starts_with('{')`
    |
    = note: #[warn(single_char_pattern)] on by default
    = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.212/index.html#single_char_pattern
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', tools/clippy/clippy_lints/src/loops.rs:491:83
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:479
   6: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   7: rust_begin_unwind
             at libstd/panicking.rs:325
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   9: core::panicking::panic_bounds_check
             at libcore/panicking.rs:59
  10: <clippy_lints::loops::Pass as rustc::lint::LateLintPass<'a, 'tcx>>::check_expr
  11: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  12: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_block
  13: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  14: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_block
  15: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  16: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_arm
  17: rustc::hir::intravisit::walk_expr
  18: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  19: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_block
  20: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  21: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_body
  22: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_nested_body
  23: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_fn
  24: rustc::hir::intravisit::walk_impl_item
  25: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_impl_item
  26: rustc::hir::intravisit::walk_impl_item_ref
  27: rustc::hir::intravisit::walk_item
  28: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item
  29: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_mod
  30: rustc::hir::intravisit::walk_item
  31: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item
  32: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_mod
  33: rustc::hir::intravisit::walk_crate
  34: rustc::lint::context::check_crate
  35: rustc::util::common::time
  36: rustc::ty::context::tls::enter_context
  37: <std::thread::local::LocalKey<T>>::with
  38: rustc::ty::context::TyCtxt::create_and_enter
  39: rustc_driver::driver::compile_input
  40: rustc_driver::run_compiler_with_pool
  41: <scoped_tls::ScopedKey<T>>::set
  42: <scoped_tls::ScopedKey<T>>::set
  43: syntax::with_globals
  44: rustc_driver::run_compiler
  45: clippy_driver::main
  46: std::rt::lang_start::{{closure}}
  47: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  48: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:106
  49: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  50: main
  51: __libc_start_main
  52: <unknown>
query stack during panic:
end of query stack
error: Could not compile `cargo`.
To learn more, run the command again with --verbose.
````

**Comment by phansch** [comment]
Thanks for the report. Looks like yesterday it still passed: https://travis-ci.org/rust-lang-nursery/rust-clippy/jobs/408764688

**Comment by matthiaskrgr** [comment]
@phansch ````cargo clippy --all```` passes locally, it's just that ````cargo clippy --all-targets --all-features```` crashes, so maybe theres some "opportunity" to increase test coverage ;)

**Comment by phansch** [comment]
Minimal repro: 

```rust
fn main() {
    let mut iter = [1].iter();
    while let Some(..) = iter.next() {
    }
}
```
