### ISSUE TITLE
crash checking markup5ever 0.7.2

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang-nursery/rust-clippy#3078]
clippy @ dda656652e2e1a8d615a712d7f7482c25fa0a9c2
````
git clone https://github.com/servo/html5ever 
cd html5ever
git checkout markup5ever-v0.7.2 
RUST_BACKTRACE=full cargo clippy --all-targets --all-features -j 1 -- --cap-lints warn -W clippy_pedantic -W clippy_nursery
````
````
    Checking markup5ever v0.7.2 (file:///tmp/m/html5ever/markup5ever)
thread 'main' panicked at 'visit_mac disabled by default', libsyntax/visit.rs:112:9
stack backtrace:
   0:     0x7f0a5d8da36e - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hd61f4c88f5b75bf2
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x7f0a5d8b3146 - std::sys_common::backtrace::print::he915412cb5f3def3
                               at libstd/sys_common/backtrace.rs:71
                               at libstd/sys_common/backtrace.rs:59
   2:     0x7f0a5d8b0c2d - std::panicking::default_hook::{{closure}}::hd9eb497a331eb03d
                               at libstd/panicking.rs:211
   3:     0x7f0a5d8b09a0 - std::panicking::default_hook::hb0ff19574f5de4d1
                               at libstd/panicking.rs:227
   4:     0x7f0a5f5d15b5 - rustc::util::common::panic_hook::h429f3af21750f1bd
   5:     0x7f0a5d8b13b3 - std::panicking::rust_panic_with_hook::h2c223612145e9a48
                               at libstd/panicking.rs:480
   6:     0x55c16eb4ac26 - std::panicking::begin_panic::h5f4c97d4ac8d820a
   7:     0x55c16eab7da8 - syntax::visit::Visitor::visit_mac::h404ae1e54b4d51dd
   8:     0x55c16eb40758 - syntax::visit::walk_pat::h9bb8ca8e37637601
   9:     0x55c16eac2492 - <clippy_lints::non_expressive_names::SimilarNamesLocalVisitor<'a, 'tcx> as syntax::visit::Visitor<'tcx>>::visit_arm::h07b7f5940b69ef23
  10:     0x55c16eb4196e - syntax::visit::walk_expr::hd8dd32d05a3e9784
  11:     0x55c16eac262a - clippy_lints::non_expressive_names::do_check::h879b3055dddbc0df
  12:     0x7f0a5f67ce5c - <rustc::lint::context::EarlyContext<'a> as syntax::visit::Visitor<'a>>::visit_item::hf21b8c605adfdc55
  13:     0x7f0a5f67f05b - <rustc::lint::context::EarlyContext<'a> as syntax::visit::Visitor<'a>>::visit_mod::h56038bfb4943e742
  14:     0x7f0a5ef8d4cc - syntax::visit::walk_item::h0132b334ffd4acf8
  15:     0x7f0a5f67cf16 - <rustc::lint::context::EarlyContext<'a> as syntax::visit::Visitor<'a>>::visit_item::hf21b8c605adfdc55
  16:     0x7f0a5f67f05b - <rustc::lint::context::EarlyContext<'a> as syntax::visit::Visitor<'a>>::visit_mod::h56038bfb4943e742
  17:     0x7f0a5ef8d4cc - syntax::visit::walk_item::h0132b334ffd4acf8
  18:     0x7f0a5f67cf16 - <rustc::lint::context::EarlyContext<'a> as syntax::visit::Visitor<'a>>::visit_item::hf21b8c605adfdc55
  19:     0x7f0a5f67f05b - <rustc::lint::context::EarlyContext<'a> as syntax::visit::Visitor<'a>>::visit_mod::h56038bfb4943e742
  20:     0x7f0a5f6824ab - rustc::lint::context::check_ast_crate::h43f66fe2f2f9fc5c
  21:     0x7f0a6036812b - rustc::util::common::time::h3fba1b994a201a62
  22:     0x7f0a6037fa90 - rustc_driver::driver::phase_2_configure_and_expand::h47bcd37b6b9a43f0
  23:     0x7f0a6037b564 - rustc_driver::driver::compile_input::h4079738fdb7427bd
  24:     0x7f0a6041fe05 - rustc_driver::run_compiler_with_pool::hee51ac9012ad0471
  25:     0x7f0a603d4669 - <scoped_tls::ScopedKey<T>>::set::hbadee0fac908344b
  26:     0x7f0a603ea378 - syntax::with_globals::hb4e652936cae7605
  27:     0x7f0a6041eee8 - rustc_driver::run_compiler::h703127a0ab5318c6
  28:     0x55c16ea95f4e - clippy_driver::main::h28c4654c724bf81b
  29:     0x55c16ea8b5a2 - std::rt::lang_start::{{closure}}::h33ffed2380737e40
  30:     0x7f0a5d8b0df2 - std::panicking::try::do_call::hbe2ca9a0512b654f
                               at libstd/rt.rs:59
                               at libstd/panicking.rs:310
  31:     0x7f0a5d8f01f9 - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:102
  32:     0x7f0a5d8c7985 - std::rt::lang_start_internal::h872b13c50744e716
                               at libstd/panicking.rs:289
                               at libstd/panic.rs:392
                               at libstd/rt.rs:58
  33:     0x55c16ea97223 - main
  34:     0x7f0a5d637222 - __libc_start_main
  35:     0x55c16ea8a468 - <unknown>
query stack during panic:
end of query stack
error: Could not compile `markup5ever`.
To learn more, run the command again with --verbose.
````

**Comment by mikerite** [comment]
The default implementation of `Visitor::visit_mac` [panics](https://github.com/rust-lang/rust/blob/35bf1ae25799a4e62131159f052e0a3cbd27c960/src/libsyntax/visit.rs#L111). If `Visitor` is implemented in a pre-expansion lint, the implementation needs to override `visit_mac`. In this case, I forgot to override it for `non_expressive_names::SimilarNamesNameVisitor` in  #3056.

I'll fix this this weekend, if no one else does it first.

It might be useful to have an internal lint to check `Visitor` implementations.

**Comment by matthiaskrgr** [comment]
For the record, this crash also happens checking ````proptest v0.7.2````.

**Comment by shepmaster** [comment]
This was noticed as the playground has [not been able to upgrade clippy](https://travis-ci.org/integer32llc/rust-playground/jobs/422382079).
